model_name: BAAI/bge-m3
model_revision: 3c06a359c08b8c49f1cab07e3eac8f846eb3a038
model_path: models/checkpoints/localization/bge-m3
weights_size_bytes: 2271064456
embedding_dimension: 1024
max_length: 64
batch_size: 32
device: cuda
precision: fp16
